### ISSUE TITLE
Input Source missing

### ISSUE THREAD

**Issue by dismaster** [SeanDorff/Sean-Dorff-s-Audio-Visualizer#2]
Would it be possible to get a input source like a Microphone?

**Comment by SeanDorff** [comment]
Thank you for your request. We will be investigating the issue shortly.

**Comment by SeanDorff** [comment]
Microphone support has been added. See readme.md for control details.

**Comment by SeanDorff** [comment]
An update version can be downloaded here: [https://github.com/SeanDorff/Sean-Dorff-s-Audio-Visualizer/releases/tag/MicrophoneSupport](https://github.com/SeanDorff/Sean-Dorff-s-Audio-Visualizer/releases/tag/MicrophoneSupport)
